feat: add product listing
sahilshakya/NoveltyMart-Ecommerce pull request #1
Opened 2024-01-16 05:12 UTC by sahilshakya

2024-01-16 07:39 UTC, AyushOmega commented on src/App.tsx
> +            <Route path="/" element={<DashboardLayout />}>
it's better to place routes in a constant file.

const uiRotues = {
    cart: '/cart',
    home: '/',
    ....
}

2024-01-16 07:40 UTC, AyushOmega commented on src/App.tsx
> +              <Route path="/singleproduct/:id" element={<Product />} />
Better name to the route would be `/products/:id`

2024-01-16 07:43 UTC, AyushOmega commented on src/components/NavBar.tsx
> +  const token = localStorage.getItem("authToken");
make a common util (`storage.ts`) where you can place functions to getItem, setItem, clear items from localstorage.

2024-01-16 07:59 UTC, AyushOmega requested changes

2024-01-16 07:59 UTC, AyushOmega commented on src/components/NavBar.tsx
> +      <ul className="flex justify-normal items-center text-normal font-bold text-gray-dark">
why `ul`? why not `div`?

2024-01-16 07:59 UTC, AyushOmega commented on src/components/NavBar.tsx
> +          <Link to="/login" className="flex items-center mx-4">
let's use value from constants.

`uiRoutes.login`

2024-01-16 07:59 UTC, AyushOmega commented on src/components/Protected.tsx
> +  return <Navigate to="/" />;
let's use value from constants.

uiRoutes.login

2024-01-16 07:59 UTC, AyushOmega commented on src/constant/api.ts
>  export const BASE_URL = "http://localhost:5000/api/v1";
API base url should reside in .env. Keep .env in .gitignore (DO NOT commit .env to remote branch).

2024-01-16 07:59 UTC, AyushOmega commented on src/login/pages/Login.tsx
> +      if (resp) {
do we think this check for `resp`?

I think, it's adequate to handle error in the error catch.

2024-01-16 07:59 UTC, AyushOmega commented on src/products/pages/Product.tsx
> +    <Link to={`/singleproduct/${product.id}`}>
take route from constant.

2024-01-16 07:59 UTC, AyushOmega commented on src/products/pages/Product.tsx
> +                ${product.price}
formatting like these should be done in a separate layer after fetching data from API.

2024-01-16 07:59 UTC, AyushOmega commented on src/products/pages/ProductsPage.tsx
> +    const response = await axios.get("http://localhost:5000/api/v1/products");
use a separate api layer.

2024-02-27 10:09 UTC, closed without merging

2024-02-27 10:09 UTC, sahilshakya commented
created new branch , with other changes